services:
  langflow:
    image: langflow:4
    pull_policy: if_not_present    
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_COMPONENTS_PATH=custom_components
    volumes:
      - langflow-data:/app/langflow
      - ./custom_components:/app/custom_components
    networks:
      - candidate_eval_app-network

networks:
  candidate_eval_app-network:
    external: true
    
volumes:
  langflow-data:
